#!/usr/bin/env -S node --experimental-transform-types

import { execFile } from 'node:child_process'
import { access } from 'node:fs/promises'
import { realpathSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import { homedir } from 'node:os'
import { dirname, isAbsolute, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { promisify } from 'node:util'

export const CLI_NAME = 'agentteams'

const sourceDirectory = dirname(fileURLToPath(import.meta.url))
const runtimeDirectory = resolve(sourceDirectory, '..')
const execFileAsync = promisify(execFile)

// Node 22's strip-only TypeScript support does not accept runtime parameter
// properties, so the CLI facade only loads compiled build:runtime artifacts.
const RUNTIME_ARTIFACTS = {
  localConfig: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'runtime', 'local-config.js'),
  localProcess: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'runtime', 'local-process.js'),
  localWorkControl: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'runtime', 'local-work-control.js'),
  relay: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'server', 'relay-process.js'),
  agent: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'runtime', 'agent-process.js'),
}

const RUNTIME_CHILD_ENTRIES = {
  relayEntry: RUNTIME_ARTIFACTS.relay,
  agentEntry: RUNTIME_ARTIFACTS.agent,
}

export const DEFAULT_CONFIG_TEXT = `# AgentTeams user config. This is the only file you normally edit.
# internal.toml, TLS and child projections are generated by the runtime.
version = 3

[bridge]
enabled = true

[agents.provider]
enabled = true
role = "provider"
label = "Local provider"

[agents.provider.identity]
hostId = "local"
machineId = "local"
accountId = "local"
agentKind = "custom"
label = "Local provider"

[agents.provider.runtime]
scopeId = "local"
dataDirectory = "data/provider"
policy = { revision = 1, allowedConsumers = ["receiver"], allowedManagers = [] }
cli = { camoExecutable = "/missing/camo", searchExecutable = "/usr/bin/rg", searchRoot = "files", profilePrefix = "teams-provider" }

[agents.provider.services.file-search]
version = "1"
operations = ["search"]
resources = [{ resourceId = "search-slot", capacity = 2, unit = "slot" }]

[agents.receiver]
enabled = true
role = "receiver"
label = "Local receiver"

[agents.receiver.identity]
hostId = "local"
machineId = "local"
accountId = "local"
agentKind = "custom"
label = "Local receiver"

[agents.receiver.runtime]
scopeId = "local"
dataDirectory = "data/receiver"
policy = { revision = 1, allowedConsumers = [], allowedManagers = [] }
cli = { camoExecutable = "/missing/camo", searchExecutable = "/usr/bin/rg", searchRoot = "files", profilePrefix = "teams-receiver" }

[agents.receiver.connect]
targetAgentId = "provider"
capabilityId = "file-search"
capabilityVersion = "1"
operation = "search"
demands = [{ resourceId = "search-slot", amount = 1 }]

[console]
enabled = false
`

export class AgentTeamsCliError extends Error {
  constructor(message) {
    super(message)
    this.name = 'AgentTeamsCliError'
  }
}

function usage() {
  return `usage: ${CLI_NAME} init|start|status|work|stop [--config <path>] [--generation <n>]`
}

function workUsage() {
  return `usage: ${CLI_NAME} work submit|query|open|request|close --config <path> [flags]`
}

function valueAfter(argv, index, flag) {
  const value = argv[index + 1]
  if (value === undefined || value.startsWith('--')) throw new AgentTeamsCliError(`${flag} requires a value`)
  return value
}

function parseArgs(argv, options) {
  const command = argv[0]
  if (command === undefined || command === 'help' || command === '--help' || command === '-h') {
    throw new AgentTeamsCliError(usage())
  }
  if (command === 'work') return parseWorkArgs(argv.slice(1), options)
  if (!['init', 'start', 'status', 'stop'].includes(command)) {
    throw new AgentTeamsCliError(`unknown command: ${command}\n${usage()}`)
  }
  const parsed = {
    command,
    configPath: options.config === undefined ? undefined : resolve(options.config),
    generation: undefined,
  }
  for (let index = 1; index < argv.length; index += 1) {
    const argument = argv[index]
    if (argument === '--config') {
      parsed.configPath = resolve(valueAfter(argv, index, argument))
      index += 1
    } else if (argument.startsWith('--config=')) {
      const value = argument.slice('--config='.length)
      if (value.length === 0) throw new AgentTeamsCliError('--config requires a value')
      parsed.configPath = resolve(value)
    } else if (argument === '--generation') {
      const raw = valueAfter(argv, index, argument)
      const generation = Number(raw)
      if (!Number.isSafeInteger(generation) || generation < 0) {
        throw new AgentTeamsCliError('--generation must be a non-negative integer')
      }
      parsed.generation = generation
      index += 1
    } else if (argument.startsWith('--generation=')) {
      const raw = argument.slice('--generation='.length)
      const generation = Number(raw)
      if (!Number.isSafeInteger(generation) || generation < 0) {
        throw new AgentTeamsCliError('--generation must be a non-negative integer')
      }
      parsed.generation = generation
    } else {
      throw new AgentTeamsCliError(`unknown argument: ${argument}\n${usage()}`)
    }
  }
  return parsed
}

function defaultConfigPath(home) {
  return resolve(home ?? homedir(), '.agentteams', 'config.toml')
}

const WORK_SUBCOMMANDS = ['submit', 'query', 'open', 'request', 'close']

function parseWorkArgs(argv, options) {
  const subcommand = argv[0]
  if (subcommand === undefined || subcommand === 'help' || subcommand === '--help' || subcommand === '-h') {
    throw new AgentTeamsCliError(workUsage())
  }
  if (!WORK_SUBCOMMANDS.includes(subcommand)) throw new AgentTeamsCliError(`unknown work subcommand: ${subcommand}\n${workUsage()}`)
  const parsed = {
    command: 'work',
    subcommand,
    configPath: options.config === undefined ? undefined : resolve(options.config),
    generation: undefined,
    payload: undefined,
    payloadProvided: false,
    workId: undefined,
    requestId: undefined,
    receiver: undefined,
    provider: undefined,
    providerGeneration: undefined,
    capabilityId: undefined,
    capabilityVersion: undefined,
    operation: undefined,
    demands: undefined,
    serviceSelection: undefined,
    linkGeneration: undefined,
  }
  const strings = { '--work-id': 'workId', '--request-id': 'requestId', '--receiver': 'receiver', '--provider': 'provider', '--capability-id': 'capabilityId', '--capability-version': 'capabilityVersion', '--operation': 'operation', '--service-selection': 'serviceSelection' }
  const integers = { '--generation': 'generation', '--provider-generation': 'providerGeneration', '--link-generation': 'linkGeneration' }
  for (let index = 1; index < argv.length; index += 1) {
    const argument = argv[index]
    const equals = argument.indexOf('=')
    const name = equals > 0 ? argument.slice(0, equals) : argument
    const inline = equals > 0 ? argument.slice(equals + 1) : undefined
    const take = flag => {
      if (inline !== undefined) {
        if (inline.length === 0) throw new AgentTeamsCliError(`${flag} requires a value`)
        return inline
      }
      const value = valueAfter(argv, index, flag)
      index += 1
      return value
    }
    if (name === '--config') {
      parsed.configPath = resolve(take(argument))
    } else if (name === '--payload') {
      const raw = take(argument)
      try { parsed.payload = JSON.parse(raw) } catch { throw new AgentTeamsCliError('--payload must be valid JSON') }
      parsed.payloadProvided = true
    } else if (name === '--demands') {
      const raw = take(argument)
      try { parsed.demands = JSON.parse(raw) } catch { throw new AgentTeamsCliError('--demands must be valid JSON') }
      if (!Array.isArray(parsed.demands)) throw new AgentTeamsCliError('--demands must be a JSON array')
    } else if (Object.hasOwn(strings, name)) {
      parsed[strings[name]] = take(argument)
    } else if (Object.hasOwn(integers, name)) {
      const value = Number(take(argument))
      if (!Number.isSafeInteger(value) || value < 0) throw new AgentTeamsCliError(`${name} must be a non-negative integer`)
      parsed[integers[name]] = value
    } else {
      throw new AgentTeamsCliError(`unknown argument: ${argument}\n${workUsage()}`)
    }
  }
  return parsed
}

function requireFlag(parsed, key, flag) {
  const value = parsed[key]
  if (value === undefined) throw new AgentTeamsCliError(`${flag} is required for work ${parsed.subcommand}`)
  return value
}

function requirePayload(parsed) {
  if (parsed.payloadProvided !== true) throw new AgentTeamsCliError(`--payload is required for work ${parsed.subcommand}`)
  return parsed.payload
}

function workReceiverCandidates(internal) {
  const candidates = []
  for (const [id, daemon] of Object.entries(internal.daemons ?? {})) {
    if (daemon.enabled === false) continue
    if (daemon.role !== 'receiver' && daemon.role !== 'hybrid') continue
    if (typeof daemon.config !== 'string') continue
    let projection
    try { projection = JSON.parse(daemon.config) } catch { continue }
    const connect = projection?.endpoint?.connect
    if (connect === null || typeof connect !== 'object' || Array.isArray(connect)) continue
    candidates.push({ id, connect })
  }
  return candidates
}

function resolveWorkReceiver(parsed, internal) {
  const candidates = workReceiverCandidates(internal)
  if (parsed.receiver !== undefined) {
    const match = candidates.find(candidate => candidate.id === parsed.receiver)
    if (match === undefined) throw new AgentTeamsCliError(`receiver ${parsed.receiver} is not an available Work receiver`)
    return match
  }
  if (candidates.length === 1) return candidates[0]
  const ids = candidates.map(candidate => candidate.id).join(', ')
  throw new AgentTeamsCliError(`expected exactly one Work receiver; pass --receiver (found ${ids.length === 0 ? 'none' : ids})`)
}

function buildWorkFrame(parsed, workControl, receiver, openTargetGeneration) {
  const connect = receiver.connect
  const base = {
    receiverAgentId: receiver.id,
    expectedLauncherGeneration: workControl.launcherGeneration,
    startToken: workControl.launcherStartToken,
    executionId: randomUUID(),
    attemptId: randomUUID(),
    workId: parsed.workId ?? randomUUID(),
    requestId: parsed.requestId ?? randomUUID(),
  }
  if (parsed.subcommand === 'submit') {
    return { kind: 'work.submit', requestId: base.requestId, control: { ...base }, business: requirePayload(parsed) }
  }
  if (parsed.subcommand === 'query') {
    if (parsed.workId === undefined || parsed.requestId === undefined) throw new AgentTeamsCliError('work query requires --work-id and --request-id')
    const selection = parsed.serviceSelection ?? 'endpoint'
    if (selection === 'capability') {
      return { kind: 'work.query', requestId: base.requestId, control: {
        ...base,
        serviceSelection: 'capability',
        targetAgentId: requireFlag(parsed, 'provider', '--provider'),
        targetGeneration: requireFlag(parsed, 'providerGeneration', '--provider-generation'),
        capabilityId: requireFlag(parsed, 'capabilityId', '--capability-id'),
        capabilityVersion: requireFlag(parsed, 'capabilityVersion', '--capability-version'),
        operation: requireFlag(parsed, 'operation', '--operation'),
        ...(parsed.linkGeneration === undefined ? {} : { linkGeneration: parsed.linkGeneration }),
      } }
    }
    if (selection !== 'endpoint') throw new AgentTeamsCliError('--service-selection must be endpoint or capability')
    return { kind: 'work.query', requestId: base.requestId, control: { ...base, serviceSelection: 'endpoint' } }
  }
  // open may derive a missing binding from the receiver's already-explicit connect
  // intent and the status projection. request/close operate on an existing Work, so
  // they must carry the exact original binding from the open receipt; the mutable
  // connect intent can never stand in for it.
  const persistent = parsed.subcommand !== 'open'
  const binding = persistent
    ? {
        targetAgentId: requireFlag(parsed, 'provider', '--provider'),
        targetGeneration: requireFlag(parsed, 'providerGeneration', '--provider-generation'),
        capabilityId: requireFlag(parsed, 'capabilityId', '--capability-id'),
        capabilityVersion: requireFlag(parsed, 'capabilityVersion', '--capability-version'),
        operation: requireFlag(parsed, 'operation', '--operation'),
      }
    : {
        targetAgentId: parsed.provider ?? connect.targetAgentId,
        targetGeneration: openTargetGeneration,
        capabilityId: parsed.capabilityId ?? connect.capabilityId,
        capabilityVersion: parsed.capabilityVersion ?? connect.capabilityVersion,
        operation: parsed.operation ?? connect.operation,
      }
  if (binding.targetAgentId === undefined || binding.targetGeneration === undefined || binding.capabilityId === undefined || binding.capabilityVersion === undefined || binding.operation === undefined) {
    throw new AgentTeamsCliError(`work ${parsed.subcommand} requires an explicit provider/capability binding`)
  }
  if (parsed.subcommand === 'open') {
    return { kind: 'work.open', requestId: base.requestId, control: { ...base, ...binding, demands: parsed.demands ?? [] }, business: requirePayload(parsed) }
  }
  if (parsed.subcommand === 'request') {
    if (parsed.workId === undefined) throw new AgentTeamsCliError('work request requires --work-id')
    return { kind: 'work.request', requestId: base.requestId, control: { ...base, ...binding, demands: parsed.demands ?? [] }, business: requirePayload(parsed) }
  }
  if (parsed.workId === undefined) throw new AgentTeamsCliError('work close requires --work-id')
  return { kind: 'work.close', requestId: base.requestId, control: { ...base, ...binding } }
}

async function resolveOpenTargetGeneration(parsed, receiver, statusLocalProcess, configPath) {
  if (parsed.providerGeneration !== undefined) return parsed.providerGeneration
  const targetAgentId = parsed.provider ?? receiver.connect.targetAgentId
  if (targetAgentId === undefined) throw new AgentTeamsCliError('work open requires an explicit provider binding before dispatch')
  const status = await statusLocalProcess(configPath)
  const endpoint = (status.endpoints ?? []).find(candidate => candidate.agentId === targetAgentId)
  if (endpoint === undefined || !Number.isSafeInteger(endpoint.generation) || endpoint.generation < 0) {
    throw new AgentTeamsCliError(`work open requires --provider-generation or a published status projection for provider ${targetAgentId}`)
  }
  return endpoint.generation
}

async function workCommand(parsed, options) {
  const runtime = options.runtime ?? await defaultRuntime()
  const localConfig = runtime.localConfig ?? (await defaultRuntime()).localConfig
  const localWorkControl = runtime.localWorkControl ?? (await defaultRuntime()).localWorkControl
  const statusLocalProcess = runtime.statusLocalProcess ?? (await defaultRuntime()).statusLocalProcess
  const configPath = parsed.configPath ?? defaultConfigPath(options.home)
  const internalPath = resolve(dirname(configPath), 'internal.toml')
  let workControl
  try { workControl = await localConfig.readLocalInternalWorkControl(internalPath) }
  catch (error) { throw new AgentTeamsCliError(`local Work control is unavailable: ${error instanceof Error ? error.message : String(error)}`) }
  if (workControl === undefined) throw new AgentTeamsCliError('local Work control is unavailable: no running launcher published a control socket')
  if (parsed.generation !== undefined && parsed.generation !== workControl.launcherGeneration) {
    throw new AgentTeamsCliError(`stale launcher generation: expected=${parsed.generation} current=${workControl.launcherGeneration}`)
  }
  const internal = await localConfig.readLocalInternalConfig(internalPath)
  const receiver = resolveWorkReceiver(parsed, internal)
  const openTargetGeneration = parsed.subcommand === 'open' ? await resolveOpenTargetGeneration(parsed, receiver, statusLocalProcess, configPath) : undefined
  const frame = buildWorkFrame(parsed, workControl, receiver, openTargetGeneration)
  const reply = await localWorkControl.sendLocalWorkControlRequest({ socketPath: workControl.socketPath, frame, ...(options.workTimeoutMs === undefined ? {} : { timeoutMs: options.workTimeoutMs }) })
  if (reply.kind === 'work.error') throw new AgentTeamsCliError(JSON.stringify({ status: 'failed', error: reply.error }))
  if (reply.receipt.status === 'failed') throw new AgentTeamsCliError(JSON.stringify(reply.receipt))
  return JSON.stringify(reply.receipt)
}

function localEnv(env) {
  const result = { ...(env ?? process.env) }
  if (result.AGENTTEAMS_PROVIDER_AUTH === undefined) result.AGENTTEAMS_PROVIDER_AUTH = 'local-provider'
  if (result.AGENTTEAMS_RECEIVER_AUTH === undefined) result.AGENTTEAMS_RECEIVER_AUTH = 'local-receiver'
  return result
}

function isNonEmptyString(value) {
  return typeof value === 'string' && value.length > 0
}

function isEndpointIdentity(value) {
  return value !== null
    && typeof value === 'object'
    && !Array.isArray(value)
    && isNonEmptyString(value.hostId)
    && isNonEmptyString(value.machineId)
    && isNonEmptyString(value.agentId)
    && isNonEmptyString(value.accountId)
    && isNonEmptyString(value.agentKind)
    && isNonEmptyString(value.label)
}

function isEndpointCapability(value) {
  return value !== null
    && typeof value === 'object'
    && !Array.isArray(value)
    && isNonEmptyString(value.capabilityId)
    && isNonEmptyString(value.version)
    && Array.isArray(value.operations)
    && value.operations.every(isNonEmptyString)
    && Array.isArray(value.resources)
    && value.resources.every(isEndpointResource)
}

function isEndpointResource(value) {
  return value !== null
    && typeof value === 'object'
    && !Array.isArray(value)
    && isNonEmptyString(value.resourceId)
    && Number.isSafeInteger(value.capacity)
    && value.capacity > 0
    && isNonEmptyString(value.unit)
}

function formatEndpoint(endpoint) {
  const id = endpoint !== null && typeof endpoint === 'object' && !Array.isArray(endpoint) && isNonEmptyString(endpoint.agentId)
    ? endpoint.agentId
    : '?'
  if (
    id === '?'
    || !isEndpointIdentity(endpoint.identity)
    || !isNonEmptyString(endpoint.role)
    || !isNonEmptyString(endpoint.presence)
    || !Number.isSafeInteger(endpoint.generation)
    || endpoint.generation < 0
    || !Array.isArray(endpoint.capabilities)
    || !endpoint.capabilities.every(isEndpointCapability)
  ) {
    return `endpoint=${id} projection=malformed`
  }
  const identity = endpoint.identity
  const capabilities = endpoint.capabilities.length === 0
    ? '-'
    : endpoint.capabilities
      .map(capability => {
        const operations = capability.operations.length === 0 ? '-' : capability.operations.join(',')
        const resources = capability.resources.length === 0
          ? '-'
          : capability.resources.map(resource => `${resource.resourceId}:${resource.capacity}:${resource.unit}`).join(',')
        return `${capability.capabilityId}@${capability.version}:${operations}[${resources}]`
      })
      .join(',')
  return `endpoint=${id} identity=${identity.hostId}/${identity.machineId}/${identity.agentId}/${identity.accountId}/${identity.agentKind}/${identity.label} role=${endpoint.role} presence=${endpoint.presence} generation=${endpoint.generation} capabilities=${capabilities}`
}

function formatStatus(prefix, status, includeEndpoints = false) {
  const pieces = [
    prefix,
    `state=${status.state}`,
    `generation=${status.generation}`,
    `config=${status.configPath}`,
    `internal=${status.internalPath}`,
  ]
  if (status.pid !== undefined) pieces.push(`pid=${status.pid}`)
  if (status.error !== undefined) pieces.push(`error=${status.error}`)
  if (includeEndpoints) {
    if (status.endpoints === undefined || status.endpoints === null) pieces.push('endpoints=missing')
    else if (!Array.isArray(status.endpoints)) pieces.push('endpoints=malformed')
    else pieces.push(...status.endpoints.map(formatEndpoint))
  }
  return pieces.join(' ')
}

async function pathExists(path) {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

let loadedRuntime

async function defaultRuntime() {
  if (loadedRuntime === undefined) {
    loadedRuntime = (async () => {
      const missing = []
      for (const [name, entry] of Object.entries(RUNTIME_ARTIFACTS)) {
        if (!(await pathExists(entry))) missing.push(`${name}: ${entry}`)
      }
      if (missing.length > 0) {
        throw new AgentTeamsCliError(`cli runtime artifacts are missing (${missing.join(', ')}); run pnpm build:runtime first`)
      }
      try {
        const [localConfig, localProcess, localWorkControl] = await Promise.all([
          import(RUNTIME_ARTIFACTS.localConfig),
          import(RUNTIME_ARTIFACTS.localProcess),
          import(RUNTIME_ARTIFACTS.localWorkControl),
        ])
        return { localConfig, localWorkControl, ...localProcess }
      } catch (error) {
        throw new AgentTeamsCliError(`cli runtime artifacts could not be loaded; run pnpm build:runtime first: ${error instanceof Error ? error.message : String(error)}`)
      }
    })()
  }
  return loadedRuntime
}

async function defaultConfigText() {
  try {
    const result = await execFileAsync('which', ['rg'])
    const executable = result.stdout.trim()
    if (!isAbsolute(executable)) throw new Error('which rg returned a non-absolute path')
    return DEFAULT_CONFIG_TEXT.replaceAll('/usr/bin/rg', executable)
  } catch (error) {
    throw new AgentTeamsCliError(`cannot locate rg executable: ${error instanceof Error ? error.message : String(error)}`)
  }
}

async function initCommand(configPath, configText, localConfig) {
  await localConfig.initializeLocalConfig(configPath, configText)
  return `initialized ${configPath}
Edit config.toml, then run ${CLI_NAME} start, ${CLI_NAME} status, or ${CLI_NAME} stop.`
}

export async function agentteamsCommand(argv = process.argv.slice(2), options = {}) {
  const parsed = parseArgs(argv, options)
  const configPath = parsed.configPath ?? defaultConfigPath(options.home)
  const env = localEnv(options.env)

  if (parsed.command === 'init') {
    const runtime = options.runtime ?? await defaultRuntime()
    const localConfig = runtime.localConfig ?? (await defaultRuntime()).localConfig
    return await initCommand(configPath, options.configText ?? await defaultConfigText(), localConfig)
  }
  if (parsed.command === 'start') {
    const runtime = options.runtime ?? await defaultRuntime()
    const status = await runtime.startLocalProcess(configPath, { env, ...RUNTIME_CHILD_ENTRIES })
    return formatStatus('started', status)
  }
  if (parsed.command === 'status') {
    const runtime = options.runtime ?? await defaultRuntime()
    const status = await runtime.statusLocalProcess(configPath)
    return formatStatus('status', status, true)
  }
  if (parsed.command === 'work') {
    return await workCommand(parsed, options)
  }
  if (parsed.command === 'stop') {
    const runtime = options.runtime ?? await defaultRuntime()
    const status = await runtime.stopLocalProcess(configPath, parsed.generation)
    return formatStatus('stopped', status)
  }
  throw new AgentTeamsCliError(`unsupported command: ${parsed.command}`)
}

export async function main(argv = process.argv.slice(2), options = {}) {
  try {
    const output = await agentteamsCommand(argv, options)
    if (output !== undefined) console.log(output)
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
  }
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  void main()
}
