#!/usr/bin/env -S node --experimental-transform-types

import { execFile } from 'node:child_process'
import { access } from 'node:fs/promises'
import { realpathSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, isAbsolute, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { promisify } from 'node:util'

export const CLI_NAME = 'agentteams'

const sourceDirectory = dirname(fileURLToPath(import.meta.url))
const runtimeDirectory = resolve(sourceDirectory, '..')
const execFileAsync = promisify(execFile)

// Node 22's strip-only TypeScript support does not accept runtime parameter
// properties, so the CLI facade only loads compiled build:runtime artifacts.
const RUNTIME_ARTIFACTS = {
  localConfig: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'runtime', 'local-config.js'),
  localProcess: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'runtime', 'local-process.js'),
  relay: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'server', 'relay-process.js'),
  agent: resolve(runtimeDirectory, 'generated', 'runtime-lib', 'runtime', 'agent-process.js'),
}

const RUNTIME_CHILD_ENTRIES = {
  relayEntry: RUNTIME_ARTIFACTS.relay,
  agentEntry: RUNTIME_ARTIFACTS.agent,
}

export const DEFAULT_CONFIG_TEXT = `# AgentTeams user config. This is the only file you normally edit.
# internal.toml, TLS and child projections are generated by the runtime.
version = 3

[bridge]
enabled = true

[agents.provider]
enabled = true
role = "provider"
label = "Local provider"

[agents.provider.identity]
hostId = "local"
machineId = "local"
accountId = "local"
agentKind = "custom"
label = "Local provider"

[agents.provider.runtime]
scopeId = "local"
dataDirectory = "data/provider"
policy = { revision = 1, allowedConsumers = ["receiver"], allowedManagers = [] }
cli = { camoExecutable = "/missing/camo", searchExecutable = "/usr/bin/rg", searchRoot = "files", profilePrefix = "teams-provider" }

[agents.provider.services.file-search]
version = "1"
operations = ["search"]
resources = [{ resourceId = "search-slot", capacity = 2, unit = "slot" }]

[agents.receiver]
enabled = true
role = "receiver"
label = "Local receiver"

[agents.receiver.identity]
hostId = "local"
machineId = "local"
accountId = "local"
agentKind = "custom"
label = "Local receiver"

[agents.receiver.runtime]
scopeId = "local"
dataDirectory = "data/receiver"
policy = { revision = 1, allowedConsumers = [], allowedManagers = [] }
cli = { camoExecutable = "/missing/camo", searchExecutable = "/usr/bin/rg", searchRoot = "files", profilePrefix = "teams-receiver" }

[agents.receiver.connect]
targetAgentId = "provider"
capabilityId = "file-search"
capabilityVersion = "1"
operation = "search"
demands = [{ resourceId = "search-slot", amount = 1 }]

[console]
enabled = false
`

export class AgentTeamsCliError extends Error {
  constructor(message) {
    super(message)
    this.name = 'AgentTeamsCliError'
  }
}

function usage() {
  return `usage: ${CLI_NAME} init|start|status|work|stop [--config <path>] [--generation <n>]`
}

function valueAfter(argv, index, flag) {
  const value = argv[index + 1]
  if (value === undefined || value.startsWith('--')) throw new AgentTeamsCliError(`${flag} requires a value`)
  return value
}

function parseArgs(argv, options) {
  const command = argv[0]
  if (command === undefined || command === 'help' || command === '--help' || command === '-h') {
    throw new AgentTeamsCliError(usage())
  }
  if (!['init', 'start', 'status', 'work', 'stop'].includes(command)) {
    throw new AgentTeamsCliError(`unknown command: ${command}\n${usage()}`)
  }
  const parsed = {
    command,
    configPath: options.config === undefined ? undefined : resolve(options.config),
    generation: undefined,
  }
  for (let index = 1; index < argv.length; index += 1) {
    const argument = argv[index]
    if (argument === '--config') {
      parsed.configPath = resolve(valueAfter(argv, index, argument))
      index += 1
    } else if (argument.startsWith('--config=')) {
      const value = argument.slice('--config='.length)
      if (value.length === 0) throw new AgentTeamsCliError('--config requires a value')
      parsed.configPath = resolve(value)
    } else if (argument === '--generation') {
      const raw = valueAfter(argv, index, argument)
      const generation = Number(raw)
      if (!Number.isSafeInteger(generation) || generation < 0) {
        throw new AgentTeamsCliError('--generation must be a non-negative integer')
      }
      parsed.generation = generation
      index += 1
    } else if (argument.startsWith('--generation=')) {
      const raw = argument.slice('--generation='.length)
      const generation = Number(raw)
      if (!Number.isSafeInteger(generation) || generation < 0) {
        throw new AgentTeamsCliError('--generation must be a non-negative integer')
      }
      parsed.generation = generation
    } else {
      throw new AgentTeamsCliError(`unknown argument: ${argument}\n${usage()}`)
    }
  }
  return parsed
}

function defaultConfigPath(home) {
  return resolve(home ?? homedir(), '.agentteams', 'config.toml')
}

function localEnv(env) {
  const result = { ...(env ?? process.env) }
  if (result.AGENTTEAMS_PROVIDER_AUTH === undefined) result.AGENTTEAMS_PROVIDER_AUTH = 'local-provider'
  if (result.AGENTTEAMS_RECEIVER_AUTH === undefined) result.AGENTTEAMS_RECEIVER_AUTH = 'local-receiver'
  return result
}

function isNonEmptyString(value) {
  return typeof value === 'string' && value.length > 0
}

function isEndpointIdentity(value) {
  return value !== null
    && typeof value === 'object'
    && !Array.isArray(value)
    && isNonEmptyString(value.hostId)
    && isNonEmptyString(value.machineId)
    && isNonEmptyString(value.agentId)
    && isNonEmptyString(value.accountId)
    && isNonEmptyString(value.agentKind)
    && isNonEmptyString(value.label)
}

function isEndpointCapability(value) {
  return value !== null
    && typeof value === 'object'
    && !Array.isArray(value)
    && isNonEmptyString(value.capabilityId)
    && isNonEmptyString(value.version)
    && Array.isArray(value.operations)
    && value.operations.every(isNonEmptyString)
    && Array.isArray(value.resources)
    && value.resources.every(isEndpointResource)
}

function isEndpointResource(value) {
  return value !== null
    && typeof value === 'object'
    && !Array.isArray(value)
    && isNonEmptyString(value.resourceId)
    && Number.isSafeInteger(value.capacity)
    && value.capacity > 0
    && isNonEmptyString(value.unit)
}

function formatEndpoint(endpoint) {
  const id = endpoint !== null && typeof endpoint === 'object' && !Array.isArray(endpoint) && isNonEmptyString(endpoint.agentId)
    ? endpoint.agentId
    : '?'
  if (
    id === '?'
    || !isEndpointIdentity(endpoint.identity)
    || !isNonEmptyString(endpoint.role)
    || !isNonEmptyString(endpoint.presence)
    || !Number.isSafeInteger(endpoint.generation)
    || endpoint.generation < 0
    || !Array.isArray(endpoint.capabilities)
    || !endpoint.capabilities.every(isEndpointCapability)
  ) {
    return `endpoint=${id} projection=malformed`
  }
  const identity = endpoint.identity
  const capabilities = endpoint.capabilities.length === 0
    ? '-'
    : endpoint.capabilities
      .map(capability => {
        const operations = capability.operations.length === 0 ? '-' : capability.operations.join(',')
        const resources = capability.resources.length === 0
          ? '-'
          : capability.resources.map(resource => `${resource.resourceId}:${resource.capacity}:${resource.unit}`).join(',')
        return `${capability.capabilityId}@${capability.version}:${operations}[${resources}]`
      })
      .join(',')
  return `endpoint=${id} identity=${identity.hostId}/${identity.machineId}/${identity.agentId}/${identity.accountId}/${identity.agentKind}/${identity.label} role=${endpoint.role} presence=${endpoint.presence} generation=${endpoint.generation} capabilities=${capabilities}`
}

function formatStatus(prefix, status, includeEndpoints = false) {
  const pieces = [
    prefix,
    `state=${status.state}`,
    `generation=${status.generation}`,
    `config=${status.configPath}`,
    `internal=${status.internalPath}`,
  ]
  if (status.pid !== undefined) pieces.push(`pid=${status.pid}`)
  if (status.error !== undefined) pieces.push(`error=${status.error}`)
  if (includeEndpoints) {
    if (status.endpoints === undefined || status.endpoints === null) pieces.push('endpoints=missing')
    else if (!Array.isArray(status.endpoints)) pieces.push('endpoints=malformed')
    else pieces.push(...status.endpoints.map(formatEndpoint))
  }
  return pieces.join(' ')
}

async function pathExists(path) {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

let loadedRuntime

async function defaultRuntime() {
  if (loadedRuntime === undefined) {
    loadedRuntime = (async () => {
      const missing = []
      for (const [name, entry] of Object.entries(RUNTIME_ARTIFACTS)) {
        if (!(await pathExists(entry))) missing.push(`${name}: ${entry}`)
      }
      if (missing.length > 0) {
        throw new AgentTeamsCliError(`cli runtime artifacts are missing (${missing.join(', ')}); run pnpm build:runtime first`)
      }
      try {
        const [localConfig, localProcess] = await Promise.all([
          import(RUNTIME_ARTIFACTS.localConfig),
          import(RUNTIME_ARTIFACTS.localProcess),
        ])
        return { localConfig, ...localProcess }
      } catch (error) {
        throw new AgentTeamsCliError(`cli runtime artifacts could not be loaded; run pnpm build:runtime first: ${error instanceof Error ? error.message : String(error)}`)
      }
    })()
  }
  return loadedRuntime
}

async function defaultConfigText() {
  try {
    const result = await execFileAsync('which', ['rg'])
    const executable = result.stdout.trim()
    if (!isAbsolute(executable)) throw new Error('which rg returned a non-absolute path')
    return DEFAULT_CONFIG_TEXT.replaceAll('/usr/bin/rg', executable)
  } catch (error) {
    throw new AgentTeamsCliError(`cannot locate rg executable: ${error instanceof Error ? error.message : String(error)}`)
  }
}

async function initCommand(configPath, configText, localConfig) {
  await localConfig.initializeLocalConfig(configPath, configText)
  return `initialized ${configPath}
Edit config.toml, then run ${CLI_NAME} start, ${CLI_NAME} status, or ${CLI_NAME} stop.`
}

export async function agentteamsCommand(argv = process.argv.slice(2), options = {}) {
  const parsed = parseArgs(argv, options)
  const configPath = parsed.configPath ?? defaultConfigPath(options.home)
  const env = localEnv(options.env)

  if (parsed.command === 'init') {
    const runtime = options.runtime ?? await defaultRuntime()
    const localConfig = runtime.localConfig ?? (await defaultRuntime()).localConfig
    return await initCommand(configPath, options.configText ?? await defaultConfigText(), localConfig)
  }
  if (parsed.command === 'start') {
    const runtime = options.runtime ?? await defaultRuntime()
    const status = await runtime.startLocalProcess(configPath, { env, ...RUNTIME_CHILD_ENTRIES })
    return formatStatus('started', status)
  }
  if (parsed.command === 'status') {
    const runtime = options.runtime ?? await defaultRuntime()
    const status = await runtime.statusLocalProcess(configPath)
    return formatStatus('status', status, true)
  }
  if (parsed.command === 'work') {
    // The selection-only v3 connect carries no Work identity, so the public
    // startup-receipt poll cannot start Work. Fail before launcher, socket or
    // provider side effects until the U4 submit/query request entry exists.
    throw new AgentTeamsCliError(`work is not implemented yet: no public new-request entry exists; ${CLI_NAME} work submit/query arrives with the U4 local-work seam`)
  }
  if (parsed.command === 'stop') {
    const runtime = options.runtime ?? await defaultRuntime()
    const status = await runtime.stopLocalProcess(configPath, parsed.generation)
    return formatStatus('stopped', status)
  }
  throw new AgentTeamsCliError(`unsupported command: ${parsed.command}`)
}

export async function main(argv = process.argv.slice(2), options = {}) {
  try {
    const output = await agentteamsCommand(argv, options)
    if (output !== undefined) console.log(output)
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
  }
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  void main()
}
